path: "..\\..\\..\\DataSets\\Fisheye8K_all_including_train&test"
# Train with fisheyes

train: "train\\images" # 5288 images fisheyes8k train
val: "test\\images"    # 2712 images fisheyes8k val
# Train with fisheyes + Woodscape

#train: "train_test_merged\\images" # 8000 images fisheyes8k train + val,10000 images Woodscapes
#val:"" #Skip val
nc: 5
names: ['Bus', 'Bike', 'Car', 'Pedestrian', 'Truck']
    